### PR TITLE
Changes from Comp2017

### PR DESCRIPTION
**Pull request by jgkamat**
See https://github.com/RoboJackets/robocup-software/pull/1001 for the master issue

### CODE REVIEW

**Review by joshhting — COMMENTED** [review]
Everything lgtm, but we should have people who actually understand radio protocol and pid to double check those sections

**Comment by jgkamat** [comment]
Everything LGTM too, but I want a :+1: from firmware before merging this :)

**Review by chachmu — APPROVED** [review]
LGTM :+1:. We will probably need to make a commit on the software PR to set the version of common to use once we merge this right?

**Comment by jgkamat** [comment]
Right now the software common (2017) should point to this branch (latest current). If more commits are added, those will need to be updated.

**Comment by petersonev** [comment]
The latest version on this branch is not compiling with firmware. I'll work on figuring out what the issue is

**Comment by jgkamat** [comment]
Are we good to merge this? @joshhting @chachmu?

**Comment by chachmu** [comment]
I need to make a quick change to get the joystick tab to display the correct information but then I think it should be good to go. We can put making them hotswapable into another issue later.

**Comment by jgkamat** [comment]
I'm merging this now, rc-software has been using it for a long time now, so there's no reason to hold back on merging it.

**Pull request merged**
