### PR TITLE
Overload [] operator for const Geometry2d::Point

### PR DESCRIPTION
**Pull request by joshhting**
This allows Geometyr2d::Point to be compatible with the new rrt.

### CODE REVIEW

**Review by jgkamat — COMMENTED** [review]
Can we change the `[]` operator defined above this to a const double instead of accessing this function? I'm not sure if anyone is using this function in a non-constant way (although they really shouldn't be).

**Comment by ashaw596** [comment]
If not theres a good bit of code duplication rn, maybe do it like this. https://stackoverflow.com/questions/856542/elegant-solution-to-duplicate-const-and-non-const-getters

**Comment by joshhting** [comment]
@jgkamat I think it's best to leave in the non-const function because I feel that someone seeing that Geometry2d::Point has a [] operator would intuitively expect the [] operator to have non-const functionality as well.

**Review by jgkamat — APPROVED** [review]
LGTM! :+1:

**Pull request merged**
